#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

"""
GTK Yadsel Tool main module
@author Marinho Brandao
@creation 2007-07-19
"""

from app import Application

application = None

def main():
    application = Application()
    application.show_form_main()

if __name__ == '__main__':
    main()

